### ISSUE TITLE
Pydantic pinned to specific version?

### ISSUE THREAD

**Issue by jmesterh** [sjoerdk/dicomtrolley#54]
Is there a reason Pydantic is pinned to 1.8.2? This is preventing us from installing dicomtrolley in our development environment, which requires >=1.10, <3. It would be great if you could relax this pin. 

Thanks!

**Comment by sjoerdk** [comment]
Hi! The pin is due to a [recursion issue with pydantic](https://github.com/pydantic/pydantic/issues/4509). If that issue is now closed but there seems to be some question whether this was really fixed or not.

This bug is exposed by this dicomtrolley test: https://github.com/sjoerdk/dicomtrolley/blob/main/tests/test_parsing.py#L111. 

If you fork the repo and remove the pin and everything runs fine (no recursion depth errors or second+ slowdowns for that particular test) I would happily accept the PR and release a new version.

Otherwise I will look at it myself, but I will probably only have time for in a few weeks

**Comment by sjoerdk** [comment]
Ok this was a bit more involved then just releasing the pin. But good to upgrade pydantic. 1.8.2 was interfering with some of my projects as well. 

Fixed in [v3.2.0](https://github.com/sjoerdk/dicomtrolley/releases/tag/v3.2.0)

**Comment by jmesterh** [comment]
Awesome, thanks so much!
